USE ROLE USERADMIN;


CREATE ROLE IF NOT EXISTS jobtech_team_role;

CREATE ROLE IF NOT EXISTS jobtech_dlt_role;      
CREATE ROLE IF NOT EXISTS jobtech_dbt_role;      
CREATE ROLE IF NOT EXISTS jobtech_streamlit_role; 


GRANT USAGE ON WAREHOUSE job_analysis_wh TO ROLE jobtech_team_role;
GRANT OPERATE ON WAREHOUSE job_analysis_wh TO ROLE jobtech_team_role;
GRANT MONITOR ON WAREHOUSE job_analysis_wh TO ROLE jobtech_team_role;

GRANT USAGE ON DATABASE Jobtech_analysis TO ROLE jobtech_team_role;
GRANT CREATE SCHEMA ON DATABASE Jobtech_analysis TO ROLE jobtech_team_role;



GRANT ALL ON SCHEMA Jobtech_analysis.staging TO ROLE jobtech_team_role;
GRANT ALL ON SCHEMA Jobtech_analysis.warehouse TO ROLE jobtech_team_role;
GRANT ALL ON SCHEMA Jobtech_analysis.marts TO ROLE jobtech_team_role;
GRANT ALL ON SCHEMA Jobtech_analysis.public TO ROLE jobtech_team_role;


GRANT ALL ON ALL TABLES IN DATABASE Jobtech_analysis TO ROLE jobtech_team_role;


GRANT ALL ON FUTURE TABLES IN DATABASE Jobtech_analysis TO ROLE jobtech_team_role;


GRANT USAGE ON WAREHOUSE job_analysis_wh TO ROLE jobtech_dlt_role;
GRANT USAGE ON DATABASE Jobtech_analysis TO ROLE jobtech_dlt_role;
GRANT CREATE SCHEMA ON DATABASE Jobtech_analysis TO ROLE jobtech_dlt_role;
GRANT ALL ON SCHEMA Jobtech_analysis.staging TO ROLE jobtech_dlt_role;
GRANT ALL ON FUTURE TABLES IN SCHEMA Jobtech_analysis.staging TO ROLE jobtech_dlt_role;


GRANT USAGE ON WAREHOUSE job_analysis_wh TO ROLE jobtech_dbt_role;
GRANT USAGE ON DATABASE Jobtech_analysis TO ROLE jobtech_dbt_role;
GRANT USAGE ON SCHEMA Jobtech_analysis.staging TO ROLE jobtech_dbt_role;
GRANT SELECT ON ALL TABLES IN SCHEMA Jobtech_analysis.staging TO ROLE jobtech_dbt_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA Jobtech_analysis.staging TO ROLE jobtech_dbt_role;
GRANT ALL ON SCHEMA Jobtech_analysis.warehouse TO ROLE jobtech_dbt_role;
GRANT ALL ON SCHEMA Jobtech_analysis.marts TO ROLE jobtech_dbt_role;
GRANT ALL ON FUTURE TABLES IN SCHEMA Jobtech_analysis.warehouse TO ROLE jobtech_dbt_role;
GRANT ALL ON FUTURE VIEWS IN SCHEMA Jobtech_analysis.warehouse TO ROLE jobtech_dbt_role;
GRANT ALL ON FUTURE TABLES IN SCHEMA Jobtech_analysis.marts TO ROLE jobtech_dbt_role;
GRANT ALL ON FUTURE VIEWS IN SCHEMA Jobtech_analysis.marts TO ROLE jobtech_dbt_role;
GRANT CREATE SCHEMA ON DATABASE Jobtech_analysis TO ROLE jobtech_dbt_role;


GRANT USAGE ON WAREHOUSE job_analysis_wh TO ROLE jobtech_streamlit_role;
GRANT USAGE ON DATABASE Jobtech_analysis TO ROLE jobtech_streamlit_role;
GRANT USAGE ON SCHEMA Jobtech_analysis.marts TO ROLE jobtech_streamlit_role;
GRANT SELECT ON ALL TABLES IN SCHEMA Jobtech_analysis.marts TO ROLE jobtech_streamlit_role;
GRANT SELECT ON ALL VIEWS IN SCHEMA Jobtech_analysis.marts TO ROLE jobtech_streamlit_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA Jobtech_analysis.marts TO ROLE jobtech_streamlit_role;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA Jobtech_analysis.marts TO ROLE jobtech_streamlit_role;
GRANT SELECT ON TABLE Jobtech_analysis.marts.MART_MAIN TO ROLE jobtech_streamlit_role;




GRANT ROLE jobtech_team_role TO USER jonathansnow;
GRANT ROLE jobtech_team_role TO USER Abbefahmi;
GRANT ROLE jobtech_team_role TO USER Abbeazeez;

GRANT ROLE jobtech_streamlit_role TO USER jonathansnow;
GRANT ROLE jobtech_streamlit_role TO USER Abbefahmi;
GRANT ROLE jobtech_streamlit_role TO USER Abbeazeez;

GRANT ROLE jobtech_dlt_role TO USER DLT_role;
GRANT ROLE jobtech_dbt_role TO USER DBT_role;
GRANT ROLE jobtech_streamlit_role TO USER Streamlit_role;


ALTER USER jonathansnow SET DEFAULT_ROLE = 'jobtech_team_role';
ALTER USER Abbefahmi SET DEFAULT_ROLE = 'jobtech_team_role';
ALTER USER Abbeazeez SET DEFAULT_ROLE = 'jobtech_team_role';

ALTER USER DLT_role SET DEFAULT_ROLE = 'jobtech_dlt_role';
ALTER USER DBT_role SET DEFAULT_ROLE = 'jobtech_dbt_role';
ALTER USER Streamlit_role SET DEFAULT_ROLE = 'jobtech_streamlit_role';



USE ROLE SYSADMIN;
USE DATABASE Jobtech_analysis;


USE ROLE SYSADMIN;
SHOW SCHEMAS IN DATABASE Jobtech_analysis;

SHOW TABLES IN SCHEMA Jobtech_analysis.STAGING;




USE ROLE jobtech_streamlit_role;
USE DATABASE JOBTECH_ANALYSIS;
USE SCHEMA MARTS;

SHOW TABLES;





USE ROLE SECURITYADMIN;

GRANT ROLE JOBTECH_DLT_ROLE TO USER DLT_ROLE;
GRANT ROLE JOBTECH_DLT_ROLE TO USER JONATHANSNOW;
SHOW GRANTS TO USER DLT_ROLE;
SHOW GRANTS TO USER JONATHANSNOW;
GRANT ROLE JOBTECH_DLT_ROLE TO USER JONATHANSNOW;

ALTER USER DLT_ROLE SET DEFAULT_ROLE = 'JOBTECH_DLT_ROLE';
ALTER USER JONATHANSNOW SET DEFAULT_ROLE = 'JOBTECH_DLT_ROLE';
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE JOB_ANALYSIS_WH TO ROLE JOBTECH_DLT_ROLE;
GRANT USAGE ON DATABASE JOBTECH_ANALYSIS TO ROLE JOBTECH_DLT_ROLE;
GRANT USAGE ON SCHEMA JOBTECH_ANALYSIS.STAGING TO ROLE JOBTECH_DLT_ROLE;
GRANT CREATE TABLE ON SCHEMA JOBTECH_ANALYSIS.STAGING TO ROLE JOBTECH_DLT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA JOBTECH_ANALYSIS.STAGING TO ROLE JOBTECH_DLT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA JOBTECH_ANALYSIS.STAGING TO ROLE JOBTECH_DLT_ROLE;

USE ROLE SYSADMIN;

SELECT table_name
FROM JOBTECH_ANALYSIS.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'STAGING';

USE ROLE SYSADMIN;

SELECT table_name
FROM JOBTECH_ANALYSIS.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'MARTS';

SELECT COUNT(*)
FROM JOBTECH_ANALYSIS.STAGING.JOB_ADS;

SELECT *
FROM JOBTECH_ANALYSIS.STAGING.JOB_ADS
LIMIT 1;

DESC TABLE JOBTECH_ANALYSIS.STAGING.JOB_ADS;

USE ROLE SYSADMIN;

SHOW SCHEMAS IN DATABASE JOBTECH_ANALYSIS;

USE ROLE SECURITYADMIN;

-- STREAMLIT ska kunna läsa rätt schema (MARTS_MARTS)
GRANT USAGE ON DATABASE JOBTECH_ANALYSIS TO ROLE JOBTECH_STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA JOBTECH_ANALYSIS.MARTS_MARTS TO ROLE JOBTECH_STREAMLIT_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA JOBTECH_ANALYSIS.MARTS_MARTS TO ROLE JOBTECH_STREAMLIT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA JOBTECH_ANALYSIS.MARTS_MARTS TO ROLE JOBTECH_STREAMLIT_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA JOBTECH_ANALYSIS.MARTS_MARTS TO ROLE JOBTECH_STREAMLIT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA JOBTECH_ANALYSIS.MARTS_MARTS TO ROLE JOBTECH_STREAMLIT_ROLE;

-- specifikt för din tabell
GRANT SELECT ON TABLE JOBTECH_ANALYSIS.MARTS_MARTS.MART_MAIN TO ROLE JOBTECH_STREAMLIT_ROLE;

USE ROLE JOBTECH_STREAMLIT_ROLE;
USE DATABASE JOBTECH_ANALYSIS;
USE SCHEMA MARTS_MARTS;

SELECT COUNT(*) FROM MART_MAIN;
