USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS g8
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = "Warehouse for analizing data from Jobtech API";

USE WAREHOUSE g8;
CREATE DATABASE IF NOT EXISTS project_hr;
USE DATABASE project_hr;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS warehouse;
CREATE SCHEMA IF NOT EXISTS mart;

DESC DATABASE project_hr;




