USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS JONATHANBARMOUSA
    PASSWORD = "1234"
    DEFAULT_WAREHOUSE = job_analysis_wh;
CREATE USER IF NOT EXISTS JONATHAN_USER
    PASSWORD = "1234"
    DEFAULT_WAREHOUSE = job_analysis_wh;    
CREATE USER IF NOT EXISTS ABBEFAHMI_USER
    PASSWORD = "1234"
    DEFAULT_WAREHOUSE = job_analysis_wh;
CREATE USER IF NOT EXISTS ABBAZEEZ_USER
    PASSWORD = "1234"
    DEFAULT_WAREHOUSE = job_analysis_wh;
CREATE USER IF NOT EXISTS DLT_role
    PASSWORD = "12345"
    DEFAULT_WAREHOUSE = job_analysis_wh;
CREATE USER IF NOT EXISTS DBT_role
    PASSWORD = "12345"
    DEFAULT_WAREHOUSE = job_analysis_wh;
CREATE USER IF NOT EXISTS Streamlit_role
    PASSWORD = "12345"
    DEFAULT_WAREHOUSE = job_analysis_wh;

SHOW users;